CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(255) PRIMARY KEY,
    auth BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS score(
username VARCHAR(50),
score INT,
FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS questions(
id INT AUTO_INCREMENT PRIMARY KEY,
question VARCHAR(255) NOT NULL,
optionA VARCHAR(50) NOT NULL,
optionB VARCHAR(50) NOT NULL,
correctAns VARCHAR(50) NOT NULL,
difficulty VARCHAR(50) NOT NULL
);